version: "3"

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    tty: true
    networks:
      - a11y-tools
      - default
    volumes:
      - ./app:/home/node/app
    command: sh -c "npm install && npm run dev"
    ports:
      - target: 3000
        published: ${WEB_PUBLISHED_PORT:-3000}
        protocol: tcp
        mode: host
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development

networks:
  a11y-tools:
    external: true
